# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, gpu]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Check out the spec of action host
      - name: set up submit script
        run:  |
          cat '#!/bin/bash' >> submit.job
          cat '#PBS -N qsub_script_test' >> submit.job
          cat '#PBS -M xuanweishan@gmail.com' >> submit.job
          cat '#PBS -m abe' >> submit.job
          cat '#PBS -q workq' >> submit.job
          cat '#PBS -k n' >> submit.job
          cat '#PBS -l walltime=72:00:00' >> submit.job
          cat '#PBS -l nodes=1:ppn=16' >> submit.job
          cat 'cd $PBSWORKDIR' >> submit.job
          cat 'mpirun -map-by ppr:1:socket:pe=4 --report-bindings ./make 1>>log' >> submit.job

      # Runs a set of commands using the runners shell
      - name: Run the test
        run: |
          echo 'run test'
          sh ./submit.job
